server:
  port: 8081

spring:
  application:
    name:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5433}/roscosmos_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

keycloak:
  auth-server-url: https://igfu.dev.roscosmos.digital/auth
  realm: rc-digital-test-vacancy
  resource: backend
#  principal-attribute: preferred_username
  credentials:
    secret: e2de4aa8-f2b6-40e4-b48f-8c0ed9ae2934
  bearer-only: true


