version: '3.8'

services:
  roscosmos_db:
    image: postgres:alpine
    restart: always
    container_name: roscosmos_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: roscosmos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
#    volumes:
#      - postgres_data:/var/lib/postgresql/data


  roscosmos-service:
    container_name: roscosmos-service
    restart: unless-stopped
    environment:
      DB_URL: roscosmos_db:5432
    build: ..
    ports:
      - "8081:8081"
    depends_on:
      - roscosmos_db


#volumes:
#  postgres_data:

  db-keycloak:
    image: postgres:alpine
    container_name: db-keycloak
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"

  keycloak:
    image: bitnami/keycloak
    container_name: keycloak
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: db-keycloak
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: postgres
      KEYCLOAK_DATABASE_PASSWORD: postgres
      KEYCLOAK_EXTRA_ARGS: --import-realm
    ports:
      - "8080:8080"
    depends_on:
      - db-keycloak
    volumes:
      - ./keycloak/roscosmos.json:/opt/bitnami/keycloak/data/import/roscosmos.json